name: Linting-and-Testing

on: [push]

jobs:

  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: Install using Bundler
        run: bundle install
      - name: Run Rubocop linter
        run: rubocop

  testing:
    name: Testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.1-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          DISCORD_FIT_BOT_DATABASE_PASSWORD: ${{ secrets.DISCORD_FIT_BOT_DATABASE_PASSWORD }}
          POSTGRES_USER: discord-fit-bot
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: Install using Bundler
        run: bundle install
      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev
      - name: Test some postgres CLI
        run: psql -l
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: discord-fit-bot
      - name: Connect to PostgreSQL
        run: |
          bin/rails db:create
          bundle exec rails db:migrate
      - name: Print env variable
        run: echo ${{ vars.TEST_VARIABLE }}
      - name: Try calling secret
        run: echo ${{ secrets.DISCORD_FIT_BOT_DATABASE_PASSWORD }}
