name: Linting

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: 'Setup Ruby and install gems'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - name: 'Run Rubocop linter'
        run: rubocop
